posts/urls.py
from django.contrib import admin
from django.urls import path
from .views import post_list, post_create, post_detail, post_update, post_delete

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('<slug>/', post_detail, name='detail'),
    path('<slug>/edit/', post_update, name='edit'),
    path('<slug>/delete/', post_delete, name='delete'),
]

tryedjango19/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    url(r'^markdownx/', include(markdownx)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from markdownx.utils import markdownify

# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    filebase, extension = filename.split('.')
    return '%s/%s' %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
            null=True, 
            blank=True,
            width_field='width_field',
            height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-timestamp', '-updated']

    def formatted_markdown(self):
        formatted_content = markdownify(self.content)
        return formatted_content

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = f'{slug} - {qs.first().id}'
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField
from .models import Post

class PostForm(forms.ModelForm):
    content = MarkdownxFormField()
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta: 
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Post

# Create your views here.
def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug):
    today = timezone.now().date()
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        'title': instance.title,
        'instance': instance,
        'share_string': share_string,
        'today': today,
    }
    return render(request, 'post_detail.html', context)

def post_list(request):
    today = timezone.now().date()
    formatted_markdown = Post.formatted_markdown
    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset_list, 2)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        'object_list': queryset,
        'title': 'Blog',
        'page_request_var': page_request_var,
        'today': today,
        'formatted_markdown': formatted_markdown,
    }
    return render(request, 'post_list.html', context)

def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, 'Deleted.')
    return redirect('posts:list')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}Blog{% endblock head_title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,800,900" rel="stylesheet"> 
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    {% block head_extra %} {% endblock head_extra %}
</head>
<body>
    {% block content %}
    {% endblock %}
<script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script>
$('.markdownx-preview').addClass('content');
</script>
</body>
</html> 

templates/messages_display.html
{% if messages %}
<article class="message is-success">
    {% for message in messages %}
    <div {% if message.tags %} class="message-body {{ message.tags }}"{% endif %}>
        <div class="columns is-mobile">
            <div class="column is-half">
                {{ message }}
            </div>
            <div class="column is-half has-text-right">
                <button class="delete" aria-label="delete"></button>
            </div>
        </div>
    </div>
    {% endfor %}
</article>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}
{% load urlify %}

{% block head_title %}
{{ block.super }} | {{ instance.title }}
{% endblock head_title %}
{% block content %}

<section class="hero is-fullheight">
    <div class="hero-head">
        {% include 'messages_display.html' %}
    </div>
    <div class="hero-body">
        <div class="container">
            <div class="columns is-mobile is-centered">
                <div class="column is-4">
                    <a href="{% url 'posts:list' %}" class="button">Back to Posts</a>
                </div>
                <div class="column is-4 has-text-right">
                    <div class="buttons is-right">
                        <a href="{% url 'posts:edit' instance.slug %}" class="button">Edit</a>
                        <a href="{% url 'posts:delete' instance.slug %}" class="button is-danger">Delete</a>
                    </div>
                </div>
            </div>
            <div class="columns is-centered">
                <div class="column is-8">
                    <h1 class="is-size-3 has-text-black  has-text-semibold">
                        {{ title }}
                        {% if instance.draft %}
                        <sup>
                            <span class="tags has-addons">
                                <span class="tag is-danger">Draft</span>
                                {% if instance.publish > today %}
                                    <span class="tag">Future Post</span>
                                {% endif %}
                            </span>
                        </sup>
                        {% endif %}
                    </h1>
                    <h1 class="is-size-6" style="margin-top: 8px;"> {{ instance.publish }}</h1>
                    {% if instance.user.get_full_name %}
                    <p class="is-size-7" style="margin-bottom: 10px;">Author: {{ instance.user.get_full_name }}</p>
                    {% endif %}
                    {% if instance.image %}
                    <figure class="image is-16by9">
                        <img src="{{ instance.image.url }}" />
                    </figure>
                    {% endif %}
                    <div class="content">
                        {{ instance.formatted_markdown|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-8">
                    <h1 class="title has-text-centered">Create Post</h1>
                    <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                        <div class="field">
                            <label for="id_title" class="label" >Title</label>
                            <div class="control">
                                {{ form.title|add_class:'input' }}
                            </div>
                        </div>
                        <div class="field">
                            <label for="id_content" class="label">Content</label>
                                {{ form.content|add_class:'textarea' }}
                        </div>
                        <hr>
                        {{ form.image }}
                        <div class="file">
                            <label class="file-label">
                                <input id="id_image" type="file" name="image" class="file-input" accept="image/*">
                                <span class="file-cta">
                                    <span class="file-icon">
                                        <i class="fas fa-upload"></i>
                                    </span>
                                    <span class="file-label">
                                        Upload Image..
                                    </span>
                                </span>
                            </label>
                        </div>
                        <div class="field" style="margin-top: 10px;">
                            <label for="id_draft" class="label checkbox">
                                Draft
                                {{ form.draft }}
                            </label>
                        </div>
                        <div class="field is-horizontal">
                            <label for="id_publish" class="label" style="margin-right: 10px;">Publish</label>
                            <div class="select is-small is-horizontal">
                                {{ form.publish }}
                            </div>
                        </div>
                        <input class="button is-info" type="submit" value="Create Post" style="margin-top: 10px;" />
                    </form>
                    {{ form.media }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<div class="hero is-fullheight">
    <div class="hero-head">
        {% include 'messages_display.html' %}
    </div>
    <div class="hero-body">
        <div class="container is-fluid">
            <h1 class="title has-text-centered">{{ title }}</h1>
                <div class="columns is-mobile is-centered">
                    <div class="column is-2-desktop is-2-mobile">
                        <a href="{% url 'posts:create' %}" class="button is-info is-size-6-mobile">+</a>
                    </div>
                    <div class="column is-6-desktop is-10-mobile">
                        <form method="GET" action="">
                            <div class="field has-addons has-addons-right">
                                <div class="control is-expanded-mobile">
                                    <input name="q" class="input" type="text" placeholder="Search posts.." value="{{ request.GET.q }}">
                                </div>
                                <div class="control">
                                    <input type="submit" class="button is-info" value="Search">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            <div class="columns is-centered is-multiline">
                {% for obj in object_list %}
                <div class="column is-4-desktop is-6-tablet">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                                <a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a>
                            </p>
                            {% if obj.draft %}
                            <span class="card-header-icon">
                                <div class="tags has-addons">
                                    <span class="tag is-danger">Draft</span>
                                    {% if obj.publish > today %}
                                    <span class="tag">Future Post</span>
                                    {% endif %}
                                </div>
                            </span>
                            {% endif %}
                        </header>
                        {% if obj.image %}
                        <div class="card-image">
                            <figure class="image is-16by9">
                                <img src="{{ obj.image.url }}">
                            </figure>
                        </div>
                        {% endif %}
                        <div class="card-content">
                            <p>
                                {{ obj.content|safe|truncatechars:20 }} 
                            </p>
                            <div class="columns is-mobile">
                                <div class="column is-half-desktop is-5-mobile centered-v">
                                    <time class="is-size-7">{{ obj.publish }}</time>
                                </div>
                                <div class="column is-half-desktop is-7-mobile has-text-right centered-v">
                                    {% if obj.user.get_full_name %}
                                    <p class="is-size-7">
                                        By {{ obj.user.get_full_name }}
                                    </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="columns is-centered">
                <div class="column is-8-desktop is-12-tablet">
                    <nav class="pagination" role="navigation" aria-label="pagination">
                            {% if object_list.has_previous %}
                                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="pagination-previous">Previous</a>
                            {% endif %}
            
                            <ul class="pagination-list">
                                <li>
                                    <a class="pagination-link is-current">
                                        {{ object_list.number }}
                                        of
                                        {{ object_list.paginator.num_pages}}
                                    </a>
                                </li>
                            </ul>
            
                            {% if object_list.has_next %}
                                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="pagination-next">Next</a>
                            {% endif %}
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}